### ISSUE TITLE
Online offline Mode

### ISSUE THREAD

**Issue by drhazrd** [sourcesync/MME_Apps#30]
As dictated By Joe:

The online offline mode very buggy and is a show stopper for me if we do not have internet.  The following needs to happen: 

Online offline mode should still remain in the config:  Internet needs to be recognized or not recognized at the start screen.  If there is internet present the experience runs as expected.  If there is no internet at the start screen the experience runs in offline mode even if the config is enabled online.  When the booth is offline the files are stored in a separated directory in the root of C:  called offline event photos.  These photos are stored and wait in a cue and instantly uploaded once the booth regains connectivity.

**Comment by sourcesync** [comment]
Alright, this will be tricky trying to do this remotely.  Let me see if i can get a windows environment running this week, i'll keep you posted.  Whats your schedule ?

**Comment by drhazrd** [comment]
As I am probably the only person able to handle this with you, whenever you can.

**Comment by Jtardi** [comment]
I'm around Wednesday.  Let me know if that works.

**Comment by sourcesync** [comment]
OK, i'll know my schedule this week after today, i'll let you know.

One if the tricky things about automatic offline/online is that sometimes internet will get very 'flakey' - it will appear offline when actually its just really slow, or its in a weird state of being brittle - going off/on/off/on very quickly.  This is likely to happen when WIFI is weak.   So, we'll make sure we can emulate these conditions for the test.

**Comment by sourcesync** [comment]
Can you guys get me a download link to the zip file for the latest release ?  Or, the ftp information ( login, pass, and path to the zip file ? )  

Thanks!

**Comment by sourcesync** [comment]
Also, are you running Windows XP or Windows 7 ?

**Comment by sourcesync** [comment]
OK, baby steps.  I have a temporary windows 7 environment and i'm downloading hercules 5.  Tuesday during the day is impossible, so i'll probably start tuesday night on the changes.

**Comment by sourcesync** [comment]
OK, i think its best to proceed in gradual steps.

I created a build which ONLY fixes issues when you set the skin configuration OFFLINE.  Please test this first and then we can proceed with auto-offline and offline-email.

The test files are in Hercules5.0/HerculesTests_OfflineConfigOnly.

Please do the following:
1) copy to a booth machine
2) setup hardware- camera and phidgets as needed
3) adjust the main config to reflect your hardware and the machine name (for license)
4) if you want to test a more recent skin, change that in the main config also and copy over the skin files
5)  if you are using a new skin, make sure OFFLINE is set to 1 in the skin config
6)  remove all the files/directories in c:\eventphotos
7) run the program and make sure it works as desired
8) you should also test by disconnecting from the network
9) notice that all the events in eventphotos have various offline related info files - these will be used later to send those emails/photos when back online ( this is not tested here )

If this all checks out, then we can move to testing offline email send, and then, auto-offline.

If you need help, lets schedule TeamViewer session preferably later in the day.

**Comment by Jtardi** [comment]
Hey George,

Thanks for the new build we were shut today due to weather.  We will test tomorrow and let you know how we make out.

Joseph Tardi
MMEInk
Jtardi@mmeink.commailto:Jtardi@mmeink.com
212.971.5353
631.777.2244

On Feb 13, 2014, at 2:52 AM, "gosha1128" <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, i think its best to proceed in gradual steps.

I created a build which ONLY fixes issues when you set the skin configuration OFFLINE. Please test this first and then we can proceed with auto-offline and offline-email.

The test files are in Hercules5.0/HerculesTests_OfflineConfigOnly.

Please do the following:
1) copy to a booth machine
2) setup hardware- camera and phidgets as needed
3) adjust the main config to reflect your hardware and the machine name (for license)
4) if you want to test a more recent skin, change that in the main config also and copy over the skin files
5) if you are using a new skin, make sure OFFLINE is set to 1 in the skin config
6) remove all the files/directories in c:\eventphotos
7) run the program and make sure it works as desired
8) you should also test by disconnecting from the network
9) notice that all the events in eventphotos have various offline related info files - these will be used later to send those emails/photos when back online ( this is not tested here )

If this all checks out, then we can move to testing offline email send, and then, auto-offline.

If you need help, lets schedule TeamViewer session preferably later in the day.

**Comment by sourcesync** [comment]
OK, I uploaded the next test package.  Warning:  This auto-offline detection is very trickey, so be patient as we slog through this.

Its here:   Hercules5.0/HerculesTests_OfflineAll_A

Instructions to Test:

1)  unzip package in a booth machine
2)  see the main config in Debug and adjust as needed for your setup
3)  locate the skin config in Skins/DoingourthingBoston and notice the two OFFLINE keys - OFFLINE is 0 meaning you are not forcing OFFLINE behavior ( as in the last test )
OFFLINE_HOST is set to a server name ( this is the server it will try to PING to determine if its online or not )

4)  either keep the same skin or use your own skin and make the necessary adjustments to that skin's config

5) clear the contents of c:/eventphotos
6) make sure you have internet so that it thinks its on-line at the outset
7) run Hercules and make sure the first experience behaves online
8) make sure you receive the email
9) now, while Hercules is running, disable the internet connection (either through system tray or disconnect network )
10) proceed through another booth experience and make sure it behaves offline ( for example, no facebook login )
11) look in eventphotos and notice the folder for the last session shows various OFFLINE files
12) now ( still while Hercules is running ) enable the network
13) notice that the OFFLINE files in that event photos session directory eventually disappear, meaning that Hercules successfully got back online and proceeded to send the photos to the server and email
14) make sure you receive the email

If anything deviates from these steps, then there are still some issues to fix

**Comment by drhazrd** [comment]
Okay after taking a look at the new build, the only issue i've come in to contact with is the lag when it generates the 4photo. I believe right after the email photo is kicked back the build tries to associate what to do with it and lags for a tick and then we get an interrupt in the experience.

**Comment by sourcesync** [comment]
Do you think this has something to do with any new offline detection code ?  

Or is the delay there all the time ( offline, online, etc? )

**Comment by drhazrd** [comment]
It could be, did you make a closed loop for checking the offline mode or is it an open reoccurring check loop?

**Comment by sourcesync** [comment]
It _should_ only check at the top of the experience, but I'll check if
there is some old code in there to do so...

-g

**Comment by sourcesync** [comment]
Hey, Nick - can i get teamview access to last source code build i put onto
one of your machines?

I seem to be missing something that i believe i only changed when i did
some quick fixes on your machine and wasn't able to checkin...

-g

**Comment by drhazrd** [comment]
Is now a good time? Or when if not now?

Thank You for your valuable time,

Nick Hatcher
Web and Marketing Director

[cid:47838C9D-495A-4C79-A1BF-206F6E9B1C93]

NYC: 147 West 35th Street, Suite 201, New York, NY 10018
Long Island: 70 Gazza Blvd, Farmingdale, NY 11735
NYC:  212.971.5353 |
Direct: 646.612.7464 |
Toll Free: 877.885.0705 x22 |
LI:  631.777.2244 |
Fax: 631.777.7176 |
eFax: 646.612.7464 |
www.mmeink.com | nhatcher@mmeink.com

**Comment by sourcesync** [comment]
Now is good...i maybe just end up zipping it up and uploading to your ftp
anyway.

-g

**Comment by drhazrd** [comment]
Okay so ill send the credentials. I set it up so that you can access it when ever you want front the management console.

Thank You for your valuable time,

Nick Hatcher
Web and Marketing Director

[cid:47838C9D-495A-4C79-A1BF-206F6E9B1C93]

NYC: 147 West 35th Street, Suite 201, New York, NY 10018
Long Island: 70 Gazza Blvd, Farmingdale, NY 11735
NYC:  212.971.5353 |
Direct: 646.612.7464 |
Toll Free: 877.885.0705 x22 |
LI:  631.777.2244 |
Fax: 631.777.7176 |
eFax: 646.612.7464 |
www.mmeink.com | nhatcher@mmeink.com

**Comment by sourcesync** [comment]
sweet, thanks.

I really want to get all the source in one repository (finally), so this
will be awesome.  It would be nice if there were a nice speedy connection
from that machine to the internet, since i will be uploading a huge zip
file, but i understand if thats not possible.

Thanks!

-g

**Comment by drhazrd** [comment]
In the right pane in the new teamveiwer the user name is "nhatcher@mmeink.com" and password is "mmeink70" you will have consistent access to it and all you'll have to do is ask us to turn it on. Good Day and WELCOME TO THE WORLD OF TOMORROW! ;)

**Comment by drhazrd** [comment]
but seriously I'm here all day

**Comment by sourcesync** [comment]
LOL, me too !

**Comment by sourcesync** [comment]
So, this machine doesn't have the last source code.

I think maybe in Dec/Jan i was actually doing developing on a machine via
TeamViewer.  Its that one.  Do you still have access to it ?

Thanks....sorry for the pain here..:)

-g

On Tue, Mar 11, 2014 at 10:54 AM, George Williams <george.williams@gmail.com

> wrote:
> 
> LOL, me too !
>

**Comment by drhazrd** [comment]
That one should still have the newest build on it you just gave us

**Comment by sourcesync** [comment]
No, that just has the binaries, no source code.

I was developing on a machine there via teamviewer ( it had VisualStudio,
all the source code etc. )

I believe it was when we were doing the last Canon camera development late
in 2013.

Is that machine still available ?  If you hook up candidate machines via
teamviewer i can check real quick...

-g

**Comment by sourcesync** [comment]
Actually, i remember now, it was a machine used for the Wall Street booth.

Can i have access to that machine?  to retrieve the last source code that i
was unable to checkin...

George

On Tue, Mar 11, 2014 at 11:09 AM, George Williams <george.williams@gmail.com

> wrote:
> 
> No, that just has the binaries, no source code.
> 
> I was developing on a machine there via teamviewer ( it had VisualStudio,
> all the source code etc. )
> 
> I believe it was when we were doing the last Canon camera development late
> in 2013.
> 
> Is that machine still available ?  If you hook up candidate machines via
> teamviewer i can check real quick...
> 
> -g
>

**Comment by drhazrd** [comment]
Joe just transferred the older build onto the machine lemme know if you can use it

Thank You for your valuable time,

Nick Hatcher
Web and Marketing Director

[cid:47838C9D-495A-4C79-A1BF-206F6E9B1C93]

NYC: 147 West 35th Street, Suite 201, New York, NY 10018
Long Island: 70 Gazza Blvd, Farmingdale, NY 11735
NYC:  212.971.5353 |
Direct: 646.612.7464 |
Toll Free: 877.885.0705 x22 |
LI:  631.777.2244 |
Fax: 631.777.7176 |
eFax: 646.612.7464 |
www.mmeink.com | nhatcher@mmeink.com

**Comment by sourcesync** [comment]
Looks like thats it.  Let me look at it...

**Comment by drhazrd** [comment]
mmeink.com/autolycus/Hercules5.0ftp://mmei7057@ftp.mmeink.com/autolycus/Hercules5.0

Thank You for your valuable time,

Nick Hatcher
Web and Marketing Director

[cid:47838C9D-495A-4C79-A1BF-206F6E9B1C93]

NYC: 147 West 35th Street, Suite 201, New York, NY 10018
Long Island: 70 Gazza Blvd, Farmingdale, NY 11735
NYC:  212.971.5353 |
Direct: 646.612.7464 |
Toll Free: 877.885.0705 x22 |
LI:  631.777.2244 |
Fax: 631.777.7176 |
eFax: 646.612.7464 |
www.mmeink.com | nhatcher@mmeink.com

**Comment by sourcesync** [comment]
Nick - can i once again have the ftp credentials ?  They are so hard to
remember...

**Comment by drhazrd** [comment]
mmei7057
Webshit2013!

I'd forget them as well and never remember them if I didn't have to use them all day. Hahaha

Thank You for your valuable time,

Nick Hatcher
Web and Marketing Director

[cid:47838C9D-495A-4C79-A1BF-206F6E9B1C93]

NYC: 147 West 35th Street, Suite 201, New York, NY 10018
Long Island: 70 Gazza Blvd, Farmingdale, NY 11735
NYC:  212.971.5353 |
Direct: 646.612.7464 |
Toll Free: 877.885.0705 x22 |
LI:  631.777.2244 |
Fax: 631.777.7176 |
eFax: 646.612.7464 |
www.mmeink.com | nhatcher@mmeink.com

**Comment by sourcesync** [comment]
OK, there is a new build to test.  Please let me know if it addresses your issue.

HerculesTest_OfflineAll_B.zip

This code merges all the changes from the build you put on the server for me, so it should contain ALL the latest changes, now including full offline support.

Remember to test these cases for offline:
1)  Setting Offline to true (and disconnecting machine from internet) should not cause delays

2)  In Offline mode, the experience should skip sending email and going to facebook.

3)  In Offline mode, the event in eventphotos directory will contain OFFLINE_ files.

4)  When you put it back to Online ( and connect machine to internet ), it should send all those emails ( and the OFFLINE_ files will disappear )

5)  If Offline was to 0, then it should detect if its online.  This you test by disconnecting/connecting the internet, and running the experience several times to make sure its properly working.

**Comment by sourcesync** [comment]
Nick, i've added you to the Hercules repository - technically, thats where all the issues for the booth code go.  So if you can start using that it would be good.  I'll migrate this issue over to it and close this one.
